In [3]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]
Neural Network Model Summary: 
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200


C:\Users\MrBinh\.conda\envs\Binh_python7\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


24/24 - 0s - loss: 1.3142 - accuracy: 0.3417
Epoch 2/200
24/24 - 0s - loss: 1.1938 - accuracy: 0.3333
Epoch 3/200
24/24 - 0s - loss: 1.1526 - accuracy: 0.3833
Epoch 4/200
24/24 - 0s - loss: 1.1298 - accuracy: 0.4833
Epoch 5/200
24/24 - 0s - loss: 1.1151 - accuracy: 0.4750
Epoch 6/200
24/24 - 0s - loss: 1.1011 - accuracy: 0.4833
Epoch 7/200
24/24 - 0s - loss: 1.0868 - accuracy: 0.4083
Epoch 8/200
24/24 - 0s - loss: 1.0736 - accuracy: 0.4417
Epoch 9/200
24/24 - 0s - loss: 1.0548 - accuracy: 0.4083
Epoch 10/200
24/24 - 0s - loss: 1.0380 - accuracy: 0.4500
Epoch 11/200
24/24 - 0s - loss: 1.0175 - accuracy: 0.5583
Epoch 12/200
24/24 - 0s - loss: 0.9936 - accuracy: 0.5833
Epoch 13/200
24/24 - 0s - loss: 0.9634 - accuracy: 0.7333
Epoch 14/200
24/24 - 0s - loss: 0.9313 - accuracy: 0.9000
Epoch 15/200
24/24 - 0s - loss: 0.9005 - accuracy: 0.8333
Epoch 16/200
24/24 - 0s - loss: 0.8554 - accuracy: 0.8917
Epoch 17/200
24/24 - 0s - loss: 0.8084 - accuracy: 0.9083
Epoch 18/200
24/24 - 0s - loss: 0.7

Epoch 142/200
24/24 - 0s - loss: 0.0816 - accuracy: 0.9750
Epoch 143/200
24/24 - 0s - loss: 0.0812 - accuracy: 0.9750
Epoch 144/200
24/24 - 0s - loss: 0.0798 - accuracy: 0.9667
Epoch 145/200
24/24 - 0s - loss: 0.0797 - accuracy: 0.9667
Epoch 146/200
24/24 - 0s - loss: 0.0806 - accuracy: 0.9667
Epoch 147/200
24/24 - 0s - loss: 0.0813 - accuracy: 0.9750
Epoch 148/200
24/24 - 0s - loss: 0.0875 - accuracy: 0.9667
Epoch 149/200
24/24 - 0s - loss: 0.0907 - accuracy: 0.9667
Epoch 150/200
24/24 - 0s - loss: 0.0776 - accuracy: 0.9667
Epoch 151/200
24/24 - 0s - loss: 0.0790 - accuracy: 0.9750
Epoch 152/200
24/24 - 0s - loss: 0.0781 - accuracy: 0.9750
Epoch 153/200
24/24 - 0s - loss: 0.0799 - accuracy: 0.9667
Epoch 154/200
24/24 - 0s - loss: 0.0793 - accuracy: 0.9750
Epoch 155/200
24/24 - 0s - loss: 0.0816 - accuracy: 0.9750
Epoch 156/200
24/24 - 0s - loss: 0.0800 - accuracy: 0.9667
Epoch 157/200
24/24 - 0s - loss: 0.0762 - accuracy: 0.9750
Epoch 158/200
24/24 - 0s - loss: 0.0775 - accuracy: 0.97

In [32]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
train_x.shape, train_y.shape, test_x.shape, test_y.shape

((120, 4), (120, 3), (30, 4), (30, 3))

In [34]:
train_y

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1

In [23]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [43]:
save_folder = 'data_nan_mean'
X_train = pd.read_csv('../data/' + save_folder + '/X_train.csv').values
y_train = pd.read_csv('../data/' + save_folder + '/y_train.csv').values
X_test = pd.read_csv('../data/' + save_folder + '/X_test.csv').values
y_test = pd.read_csv('../data/' + save_folder + '/y_test.csv').values

y_train = np.squeeze(y_train)
n_values = np.max(y_train) + 1
y_train = np.eye(n_values)[y_train]

y_test = np.squeeze(y_test)
n_values = np.max(y_test) + 1
y_test = np.eye(n_values)[y_test]

In [59]:
model = Sequential()

model.add(Dense(16, input_shape=(9,), activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax', name='output'))

optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print(model.summary())

model.fit(X_train, y_train, verbose=2, batch_size=16, epochs=300)
results = model.evaluate(X_test, y_test)

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 16)                160       
_________________________________________________________________
dense_11 (Dense)             (None, 16)                272       
_________________________________________________________________
output (Dense)               (None, 3)                 51        
Total params: 483
Trainable params: 483
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/300
17/17 - 0s - loss: 256.6971 - accuracy: 0.3676
Epoch 2/300
17/17 - 0s - loss: 139.9102 - accuracy: 0.3346
Epoch 3/300
17/17 - 0s - loss: 52.0885 - accuracy: 0.2831
Epoch 4/300
17/17 - 0s - loss: 12.2342 - accuracy: 0.2904
Epoch 5/300
17/17 - 0s - loss: 9.0095 - accuracy: 0.3235
Epoch 6/300
17/17 - 0s - loss: 3.7384 - accuracy: 0.3162
Epoch 7/300
17/17 - 0s - loss: 3

Epoch 129/300
17/17 - 0s - loss: 0.9897 - accuracy: 0.6507
Epoch 130/300
17/17 - 0s - loss: 0.3436 - accuracy: 0.8603
Epoch 131/300
17/17 - 0s - loss: 0.5286 - accuracy: 0.8051
Epoch 132/300
17/17 - 0s - loss: 0.7077 - accuracy: 0.7831
Epoch 133/300
17/17 - 0s - loss: 0.5200 - accuracy: 0.7904
Epoch 134/300
17/17 - 0s - loss: 0.8316 - accuracy: 0.7022
Epoch 135/300
17/17 - 0s - loss: 0.2584 - accuracy: 0.9191
Epoch 136/300
17/17 - 0s - loss: 0.5906 - accuracy: 0.7610
Epoch 137/300
17/17 - 0s - loss: 0.4063 - accuracy: 0.8162
Epoch 138/300
17/17 - 0s - loss: 0.1824 - accuracy: 0.9522
Epoch 139/300
17/17 - 0s - loss: 0.5556 - accuracy: 0.7721
Epoch 140/300
17/17 - 0s - loss: 0.4635 - accuracy: 0.8088
Epoch 141/300
17/17 - 0s - loss: 0.4697 - accuracy: 0.8125
Epoch 142/300
17/17 - 0s - loss: 0.4488 - accuracy: 0.8456
Epoch 143/300
17/17 - 0s - loss: 0.2365 - accuracy: 0.9265
Epoch 144/300
17/17 - 0s - loss: 0.3507 - accuracy: 0.8382
Epoch 145/300
17/17 - 0s - loss: 0.5227 - accuracy: 0.77

Epoch 268/300
17/17 - 0s - loss: 0.2521 - accuracy: 0.8971
Epoch 269/300
17/17 - 0s - loss: 0.2609 - accuracy: 0.8860
Epoch 270/300
17/17 - 0s - loss: 0.2746 - accuracy: 0.8897
Epoch 271/300
17/17 - 0s - loss: 0.5955 - accuracy: 0.7537
Epoch 272/300
17/17 - 0s - loss: 0.1497 - accuracy: 0.9522
Epoch 273/300
17/17 - 0s - loss: 0.1455 - accuracy: 0.9412
Epoch 274/300
17/17 - 0s - loss: 0.2239 - accuracy: 0.8934
Epoch 275/300
17/17 - 0s - loss: 0.4649 - accuracy: 0.8272
Epoch 276/300
17/17 - 0s - loss: 0.2794 - accuracy: 0.8971
Epoch 277/300
17/17 - 0s - loss: 0.2718 - accuracy: 0.8860
Epoch 278/300
17/17 - 0s - loss: 0.1598 - accuracy: 0.9338
Epoch 279/300
17/17 - 0s - loss: 0.1017 - accuracy: 0.9669
Epoch 280/300
17/17 - 0s - loss: 0.1211 - accuracy: 0.9485
Epoch 281/300
17/17 - 0s - loss: 0.1451 - accuracy: 0.9485
Epoch 282/300
17/17 - 0s - loss: 0.3058 - accuracy: 0.8860
Epoch 283/300
17/17 - 0s - loss: 0.1825 - accuracy: 0.9191
Epoch 284/300
17/17 - 0s - loss: 0.6308 - accuracy: 0.79

In [33]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((272, 9), (272, 1), (70, 9), (70, 1))

In [40]:
n_values = np.max(np.squeeze(y_train)) + 1
np.eye(n_values)[np.squeeze(y_train)]

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [41]:
y_train

array([[2],
       [1],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [2],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [2],
       [2],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [0],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [0],
       [0],
       [2],
       [2],
       [2],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
    